services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    env_file:
      - .env
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} && pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_TEST}"]
      interval: 10s
      timeout: 5s
      retries: 5

  social_media_api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: saikrishna59/fastapi-social_media_api:latest
    container_name: social_media_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 8000:8000   
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 8888:80
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin_data: